services:
  api-service:
    build:
      context: .
      dockerfile: services/api-service/Dockerfile
    container_name: rag_api
    ports:
      - "8000:8000"
    environment:
      - qdrant_cluster_endpoint=${qdrant_cluster_endpoint}
      - qdrant_api_key=${qdrant_api_key}
      - JWT_SECRET=change_me_local_development_only
      - LOG_LEVEL=INFO
      - AWS_REGION=ap-south-1
      - AWS_DEFAULT_REGION=ap-south-1
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - rag_network
    restart: unless-stopped

networks:
  rag_network:
    driver: bridge
